name: Waka Readme

on:
  schedule:
    # Runs at 11:30 AM ICT (4:30 AM UTC)
    - cron: '40 4 * * *'
  workflow_dispatch:


jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: 'false'   # Show total coding time
          SHOW_LANGUAGE: 'false'          # Hide languages used
          SHOW_LINES_OF_CODE: 'false'     # Hide lines of code
          SHOW_TIME: 'false'              # Hide individual coding time (for each language, etc.)
          SHOW_MASKED_TIME: 'false'       # Hide masked time (if any)
          SHOW_TITLE: 'false'             # Hide title or header section
          SHOW_PROFILE_VIEWS: 'false'     # Hide Profile View
          SHOW_LOC_CHART: 'false'         # Hide LOC Chart 
          SHOW_COMMIT: 'false'            # Hide Commit
          SHOW_DAYS_OF_WEEK: 'false'      # Hide Days of WEEK
          SHOW_SHORT_INFO: 'false'        # Hide Short Info
          SHOW_OS: 'false'
          SHOW_PROJECTS: 'false'
          SHOW_TIMEZONE: 'false'
          SHOW_EDITORS: 'false'
          
          
          
          
